version: '3'
services:
  node:
    image: node:17-alpine
    volumes:
      - './:/app/'
    working_dir: /app
    restart: unless-stopped
    tty: true
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run start"
    environment:
      NODE_OPTIONS: --openssl-legacy-provider