version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true 
          node-version: v18.9.0 
          yarn-version: '1.22.19'
      - run: yarn install
      - run: yarn run build
workflows:
  build-and-test:
    jobs:
      - build