version: 2.1
orbs:
  node: circleci/node@4.5.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
workflows:
    build-and-test:
      jobs:
        - build-and-test